# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: options.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\roptions.proto\x12#privacysandbox.apis.roma.app_api.v1\x1a google/protobuf/descriptor.proto\"\xd3\x01\n\x15RomaServiceAnnotation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ode_id\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x15\n\rcpp_namespace\x18\x04 \x01(\t\x12\x15\n\rroma_app_name\x18\x05 \x01(\t\x12\x18\n\x10\x63sharp_namespace\x18\x07 \x01(\t\x12\x12\n\ngo_package\x18\x08 \x01(\t\x12*\n\"cpp_host_process_callback_includes\x18\x06 \x03(\t\"P\n\x16RomaFunctionAnnotation\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12!\n\x19\x63pp_host_process_callback\x18\x02 \x01(\t\"*\n\x13RomaFieldAnnotation\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\",\n\x15RomaMessageAnnotation\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t:z\n\x13roma_svc_annotation\x12\x1f.google.protobuf.ServiceOptions\x18\xd0\x86\x03 \x01(\x0b\x32:.privacysandbox.apis.roma.app_api.v1.RomaServiceAnnotation:z\n\x13roma_rpc_annotation\x12\x1e.google.protobuf.MethodOptions\x18\xd1\x86\x03 \x01(\x0b\x32;.privacysandbox.apis.roma.app_api.v1.RomaFunctionAnnotation:x\n\x15roma_field_annotation\x12\x1d.google.protobuf.FieldOptions\x18\xd2\x86\x03 \x01(\x0b\x32\x38.privacysandbox.apis.roma.app_api.v1.RomaFieldAnnotation:{\n\x14roma_mesg_annotation\x12\x1f.google.protobuf.MessageOptions\x18\xd3\x86\x03 \x01(\x0b\x32:.privacysandbox.apis.roma.app_api.v1.RomaMessageAnnotation:v\n\x14roma_enum_annotation\x12\x1c.google.protobuf.EnumOptions\x18\xd4\x86\x03 \x01(\x0b\x32\x38.privacysandbox.apis.roma.app_api.v1.RomaFieldAnnotation:~\n\x17roma_enumval_annotation\x12!.google.protobuf.EnumValueOptions\x18\xd5\x86\x03 \x01(\x0b\x32\x38.privacysandbox.apis.roma.app_api.v1.RomaFieldAnnotationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROMASERVICEANNOTATION']._serialized_start=89
  _globals['_ROMASERVICEANNOTATION']._serialized_end=300
  _globals['_ROMAFUNCTIONANNOTATION']._serialized_start=302
  _globals['_ROMAFUNCTIONANNOTATION']._serialized_end=382
  _globals['_ROMAFIELDANNOTATION']._serialized_start=384
  _globals['_ROMAFIELDANNOTATION']._serialized_end=426
  _globals['_ROMAMESSAGEANNOTATION']._serialized_start=428
  _globals['_ROMAMESSAGEANNOTATION']._serialized_end=472
# @@protoc_insertion_point(module_scope)
